version: '3.9'

services:
  app:
    build: .
    container_name: node.js
    ports:
      - 443:443
      - 80:80
    volumes:
      - /Users/breno/GolandProjects/Projeto Escola/app:/home/node/app
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 10152030
    volumes:
      - /Users/breno/GolandProjects/Projeto Escola/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

